"""
Clinic Report Generator
=======================

Generates quarterly PDF reports for clinics participating in the PATH Lab study.
Shows aggregate outcomes, response rates, and comparisons to study-wide averages.

Uses PATH Lab branding:
- Colors: #394F79 (primary), #253D6C (dark), #7E846F (sage), #FFEFDD (cream)
- Font: Montserrat
"""

import pandas as pd
import numpy as np
from pathlib import Path
from datetime import datetime
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.image as mpimg
from matplotlib.backends.backend_pdf import PdfPages

# PATH Lab Brand Colors
COLORS = {
    'primary': '#394F79',      # Primary blue
    'dark': '#253D6C',         # Dark blue
    'sage': '#7E846F',         # Sage green
    'cream': '#FFEFDD',        # Cream background
    'white': '#FFFFFF',
    'light_gray': '#E8E8E8',
    'success': '#4A7C59',      # Green for improvement
    'warning': '#D4A84B',      # Yellow for no change
    'danger': '#A85454',       # Red for worsening
    'light_primary': '#5A7099',
}

# Clinical thresholds
PHQ9_RESPONSE_THRESHOLD = 0.50  # 50% reduction = response
PHQ9_REMISSION_THRESHOLD = 5    # Score < 5 = remission
GAD7_RESPONSE_THRESHOLD = 0.50
GAD7_REMISSION_THRESHOLD = 5
WHO5_CLINICALLY_LOW = 28        # Suggests depression screening

# Timepoint labels
TIMEPOINT_LABELS = {
    'bl': 'Baseline',
    '3d': '3 Days',
    '1mo': '1 Month',
    '3mo': '3 Months',
    '6mo': '6 Months',
    '12mo': '12 Months',
}


def setup_figure_style():
    """Set up matplotlib style for PATH Lab branding."""
    plt.rcParams['font.family'] = 'sans-serif'
    plt.rcParams['font.sans-serif'] = ['Montserrat', 'Arial', 'Helvetica', 'DejaVu Sans']
    plt.rcParams['font.size'] = 10
    plt.rcParams['axes.titlesize'] = 12
    plt.rcParams['axes.labelsize'] = 10
    plt.rcParams['axes.titleweight'] = 'bold'
    plt.rcParams['axes.spines.top'] = False
    plt.rcParams['axes.spines.right'] = False
    plt.rcParams['axes.edgecolor'] = COLORS['primary']
    plt.rcParams['axes.labelcolor'] = COLORS['dark']
    plt.rcParams['xtick.color'] = COLORS['dark']
    plt.rcParams['ytick.color'] = COLORS['dark']
    plt.rcParams['figure.facecolor'] = COLORS['white']
    plt.rcParams['axes.facecolor'] = COLORS['white']


def create_header(fig, clinic_name, report_type, report_date, page_num=1, total_pages=2, logo_dir=None):
    """Create report header with PATH Lab branding and logo."""
    header_ax = fig.add_axes([0, 0.92, 1, 0.08])
    header_ax.set_facecolor(COLORS['cream'])
    header_ax.set_xlim(0, 1)
    header_ax.set_ylim(0, 1)
    header_ax.axis('off')

    # Try to load and display logo
    if logo_dir:
        try:
            logo = mpimg.imread(logo_dir / 'PATHLogo.png')
            logo_ax = fig.add_axes([0.02, 0.925, 0.15, 0.065])
            logo_ax.imshow(logo)
            logo_ax.axis('off')
        except Exception:
            pass

    # Report info on right
    header_ax.text(0.97, 0.65, f'{report_type} Clinic Report', fontsize=12,
                   color=COLORS['primary'], va='center', ha='right', fontweight='bold')
    header_ax.text(0.97, 0.30, f'{clinic_name}  |  {report_date}  |  Page {page_num}/{total_pages}',
                   fontsize=9, color=COLORS['dark'], va='center', ha='right')


def create_footer(fig, logo_dir=None):
    """Create report footer with logos and attribution."""
    footer_ax = fig.add_axes([0, 0, 1, 0.06])
    footer_ax.set_facecolor(COLORS['cream'])
    footer_ax.set_xlim(0, 1)
    footer_ax.set_ylim(0, 1)
    footer_ax.axis('off')

    # Try to load and display logos
    if logo_dir:
        try:
            path_logo = mpimg.imread(logo_dir / 'PATHLogo.png')
            logo_ax = fig.add_axes([0.02, 0.008, 0.12, 0.045])
            logo_ax.imshow(path_logo)
            logo_ax.axis('off')
        except Exception:
            pass

        # Try New School logo (PNG version)
        try:
            ns_logo = mpimg.imread(logo_dir / 'newschool_logo.png')
            ns_ax = fig.add_axes([0.15, 0.008, 0.12, 0.045])
            ns_ax.imshow(ns_logo)
            ns_ax.axis('off')
        except Exception:
            pass

    # Attribution text
    footer_ax.text(0.5, 0.7, 'This report was generated by the PATH Lab at the New School for Social Research',
                   ha='center', va='center', fontsize=7, color=COLORS['dark'], style='italic')
    footer_ax.text(0.5, 0.25, 'Confidential - For clinic use only.',
                   ha='center', va='center', fontsize=6, color=COLORS['sage'], style='italic')


def calculate_clinic_metrics(df, timepoint='1mo'):
    """Calculate key clinic metrics."""
    metrics = {}

    # Sample size
    metrics['n_total'] = len(df)

    # Calculate response and remission rates for PHQ-9
    has_bl_phq9 = df['phq9_total_bl'].notna()
    has_tp_phq9 = df[f'phq9_total_{timepoint}'].notna()
    has_both_phq9 = has_bl_phq9 & has_tp_phq9

    if has_both_phq9.sum() > 0:
        subset = df[has_both_phq9]
        bl_scores = subset['phq9_total_bl']
        tp_scores = subset[f'phq9_total_{timepoint}']

        # Response: >= 50% reduction
        pct_reduction = (bl_scores - tp_scores) / bl_scores
        metrics['phq9_response_rate'] = (pct_reduction >= PHQ9_RESPONSE_THRESHOLD).mean() * 100
        metrics['phq9_response_n'] = has_both_phq9.sum()

        # Remission: score < 5
        metrics['phq9_remission_rate'] = (tp_scores < PHQ9_REMISSION_THRESHOLD).mean() * 100

        # Average change
        metrics['phq9_mean_change'] = (tp_scores - bl_scores).mean()
        metrics['phq9_mean_bl'] = bl_scores.mean()
        metrics['phq9_mean_tp'] = tp_scores.mean()
    else:
        metrics['phq9_response_rate'] = np.nan
        metrics['phq9_remission_rate'] = np.nan
        metrics['phq9_mean_change'] = np.nan

    # Same for GAD-7
    has_bl_gad7 = df['gad7_total_bl'].notna()
    has_tp_gad7 = df[f'gad7_total_{timepoint}'].notna()
    has_both_gad7 = has_bl_gad7 & has_tp_gad7

    if has_both_gad7.sum() > 0:
        subset = df[has_both_gad7]
        bl_scores = subset['gad7_total_bl']
        tp_scores = subset[f'gad7_total_{timepoint}']

        pct_reduction = (bl_scores - tp_scores) / bl_scores
        metrics['gad7_response_rate'] = (pct_reduction >= GAD7_RESPONSE_THRESHOLD).mean() * 100
        metrics['gad7_response_n'] = has_both_gad7.sum()
        metrics['gad7_remission_rate'] = (tp_scores < GAD7_REMISSION_THRESHOLD).mean() * 100
        metrics['gad7_mean_change'] = (tp_scores - bl_scores).mean()
        metrics['gad7_mean_bl'] = bl_scores.mean()
        metrics['gad7_mean_tp'] = tp_scores.mean()
    else:
        metrics['gad7_response_rate'] = np.nan
        metrics['gad7_remission_rate'] = np.nan
        metrics['gad7_mean_change'] = np.nan

    # WHO-5 improvement
    has_bl_who5 = df['who5_total_bl'].notna()
    has_tp_who5 = df[f'who5_total_{timepoint}'].notna()
    has_both_who5 = has_bl_who5 & has_tp_who5

    if has_both_who5.sum() > 0:
        subset = df[has_both_who5]
        bl_scores = subset['who5_total_bl']
        tp_scores = subset[f'who5_total_{timepoint}']

        # Clinically meaningful improvement (10+ points)
        improvement = tp_scores - bl_scores
        metrics['who5_improved_rate'] = (improvement >= 10).mean() * 100
        metrics['who5_response_n'] = has_both_who5.sum()
        metrics['who5_mean_change'] = improvement.mean()
        metrics['who5_mean_bl'] = bl_scores.mean()
        metrics['who5_mean_tp'] = tp_scores.mean()
    else:
        metrics['who5_improved_rate'] = np.nan
        metrics['who5_mean_change'] = np.nan

    # MEQ scores (mystical experience at 3d)
    if 'meq4_total_3d' in df.columns:
        meq_scores = df['meq4_total_3d'].dropna()
        if len(meq_scores) > 0:
            metrics['meq_mean'] = meq_scores.mean()
            metrics['meq_complete_rate'] = (meq_scores >= 3.0).mean() * 100  # Complete mystical = mean >= 3
            metrics['meq_n'] = len(meq_scores)
        else:
            metrics['meq_mean'] = np.nan

    return metrics


def create_kpi_card(ax, value, label, subtitle='', color=COLORS['primary'], is_percent=True):
    """Create a KPI card visualization."""
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis('off')

    # Background
    rect = mpatches.FancyBboxPatch((0.05, 0.1), 0.9, 0.8,
                                    boxstyle="round,pad=0.02",
                                    facecolor=COLORS['cream'], alpha=0.5,
                                    edgecolor=color, linewidth=2)
    ax.add_patch(rect)

    # Value
    if pd.isna(value):
        value_str = 'N/A'
    elif is_percent:
        value_str = f'{value:.0f}%'
    else:
        value_str = f'{int(value)}'

    ax.text(0.5, 0.65, value_str, fontsize=24, fontweight='bold',
            ha='center', va='center', color=color)

    # Label
    ax.text(0.5, 0.30, label, fontsize=10, fontweight='bold',
            ha='center', va='center', color=COLORS['dark'])

    if subtitle:
        ax.text(0.5, 0.12, subtitle, fontsize=8,
                ha='center', va='center', color=COLORS['sage'])


def create_bar_comparison(ax, clinic_value, study_value, label, is_percent=True, higher_is_better=True):
    """Create a horizontal bar comparing clinic to study average."""
    ax.set_xlim(0, 100 if is_percent else max(clinic_value or 0, study_value or 0) * 1.2)
    ax.set_ylim(0, 1)
    ax.axis('off')

    bar_height = 0.25

    # Study average bar
    if not pd.isna(study_value):
        ax.barh(0.65, study_value, height=bar_height, color=COLORS['light_gray'],
                edgecolor=COLORS['sage'], label='Study Avg')

    # Clinic bar
    if not pd.isna(clinic_value):
        # Color based on performance
        if higher_is_better:
            bar_color = COLORS['success'] if clinic_value >= (study_value or 0) else COLORS['warning']
        else:
            bar_color = COLORS['success'] if clinic_value <= (study_value or 0) else COLORS['warning']
        ax.barh(0.35, clinic_value, height=bar_height, color=bar_color,
                edgecolor=COLORS['dark'], label='Your Clinic')

    # Labels
    ax.text(0, 0.95, label, fontsize=10, fontweight='bold', color=COLORS['dark'])

    suffix = '%' if is_percent else ''
    if not pd.isna(clinic_value):
        ax.text(clinic_value + 2, 0.35, f'{clinic_value:.1f}{suffix}', fontsize=9,
                va='center', color=COLORS['dark'], fontweight='bold')
    if not pd.isna(study_value):
        ax.text(study_value + 2, 0.65, f'{study_value:.1f}{suffix}', fontsize=9,
                va='center', color=COLORS['sage'])

    # Legend
    ax.text(0.98, 0.65, 'Study', fontsize=8, color=COLORS['sage'],
            ha='right', va='center', transform=ax.transAxes)
    ax.text(0.98, 0.35, 'Clinic', fontsize=8, color=COLORS['dark'],
            ha='right', va='center', transform=ax.transAxes)


def create_score_trajectory(ax, df, measure, timepoints, label, y_range):
    """Create a line chart showing average scores over time with confidence bands."""
    means = []
    stds = []
    ns = []

    for tp in timepoints:
        col = f'{measure}_total_{tp}'
        if col in df.columns:
            scores = df[col].dropna()
            means.append(scores.mean() if len(scores) > 0 else np.nan)
            stds.append(scores.std() if len(scores) > 0 else np.nan)
            ns.append(len(scores))
        else:
            means.append(np.nan)
            stds.append(np.nan)
            ns.append(0)

    x = range(len(timepoints))
    valid_mask = [not pd.isna(m) for m in means]

    if not any(valid_mask):
        ax.text(0.5, 0.5, 'No data available', ha='center', va='center',
                fontsize=11, color=COLORS['sage'], transform=ax.transAxes)
        ax.set_title(label, fontweight='bold', color=COLORS['dark'])
        return

    # Filter to valid points
    valid_x = [xi for xi, v in zip(x, valid_mask) if v]
    valid_means = [m for m, v in zip(means, valid_mask) if v]
    valid_stds = [s for s, v in zip(stds, valid_mask) if v]

    # Confidence band (mean +/- SE)
    valid_ns = [n for n, v in zip(ns, valid_mask) if v]
    se = [s / np.sqrt(n) if n > 1 else 0 for s, n in zip(valid_stds, valid_ns)]
    lower = [m - 1.96 * e for m, e in zip(valid_means, se)]
    upper = [m + 1.96 * e for m, e in zip(valid_means, se)]

    ax.fill_between(valid_x, lower, upper, alpha=0.2, color=COLORS['primary'])
    ax.plot(valid_x, valid_means, 'o-', color=COLORS['primary'], linewidth=2.5,
            markersize=8, markerfacecolor=COLORS['white'], markeredgewidth=2)

    # Add n labels
    for xi, yi, n in zip(valid_x, valid_means, valid_ns):
        ax.annotate(f'n={n}', (xi, yi), textcoords="offset points",
                    xytext=(0, 10), ha='center', fontsize=8, color=COLORS['sage'])

    ax.set_xlim(-0.5, len(timepoints) - 0.5)
    ax.set_ylim(y_range)
    ax.set_xticks(range(len(timepoints)))
    ax.set_xticklabels([TIMEPOINT_LABELS.get(tp, tp) for tp in timepoints], fontsize=9)
    ax.set_title(label, fontweight='bold', color=COLORS['dark'], pad=10)
    ax.set_ylabel('Mean Score', fontsize=9)
    ax.grid(True, axis='y', alpha=0.3, color=COLORS['sage'])


def create_distribution_chart(ax, df, measure, timepoints, label):
    """Create box plots showing score distributions across timepoints."""
    data = []
    positions = []
    labels = []

    for i, tp in enumerate(timepoints):
        col = f'{measure}_total_{tp}'
        if col in df.columns:
            scores = df[col].dropna()
            if len(scores) > 0:
                data.append(scores.values)
                positions.append(i)
                labels.append(TIMEPOINT_LABELS.get(tp, tp))

    if not data:
        ax.text(0.5, 0.5, 'No data', ha='center', va='center',
                fontsize=11, color=COLORS['sage'], transform=ax.transAxes)
        ax.set_title(label, fontweight='bold', color=COLORS['dark'])
        return

    bp = ax.boxplot(data, positions=positions, widths=0.6, patch_artist=True)

    for box in bp['boxes']:
        box.set_facecolor(COLORS['cream'])
        box.set_edgecolor(COLORS['primary'])
        box.set_linewidth(1.5)
    for whisker in bp['whiskers']:
        whisker.set_color(COLORS['primary'])
    for cap in bp['caps']:
        cap.set_color(COLORS['primary'])
    for median in bp['medians']:
        median.set_color(COLORS['dark'])
        median.set_linewidth(2)
    for flier in bp['fliers']:
        flier.set_markerfacecolor(COLORS['sage'])
        flier.set_markeredgecolor(COLORS['sage'])

    ax.set_xticks(positions)
    ax.set_xticklabels(labels, fontsize=9)
    ax.set_title(label, fontweight='bold', color=COLORS['dark'], pad=10)
    ax.grid(True, axis='y', alpha=0.3, color=COLORS['sage'])


def generate_clinic_report(df, clinic_name, report_type, output_path, study_df=None):
    """
    Generate a quarterly PDF report for a clinic.

    Parameters:
    -----------
    df : DataFrame
        Clinic's participant data (wide format)
    clinic_name : str
        Name of the clinic
    report_type : str
        'Q2' or 'Q4' (determines timepoints shown)
    output_path : Path
        Where to save the PDF
    study_df : DataFrame, optional
        Full study data for comparison (defaults to clinic data)
    """
    setup_figure_style()

    if study_df is None:
        study_df = df  # Use clinic data as study data if not provided

    # Determine timepoints based on report type
    if report_type == 'Q2':
        timepoints = ['bl', '1mo', '3mo']
        primary_timepoint = '3mo'
        report_title = 'Q2 (Mid-Year)'
    else:  # Q4
        timepoints = ['bl', '1mo', '3mo', '6mo', '12mo']
        primary_timepoint = '6mo'
        report_title = 'Q4 (Annual)'

    report_date = datetime.now().strftime('%B %Y')
    logo_dir = Path(output_path).parent

    # Calculate metrics
    clinic_metrics = calculate_clinic_metrics(df, primary_timepoint)
    study_metrics = calculate_clinic_metrics(study_df, primary_timepoint)

    # === PAGE 1: Key Metrics & Response Rates ===
    fig1 = plt.figure(figsize=(8.5, 11))
    create_header(fig1, clinic_name, report_title, report_date, page_num=1, total_pages=2, logo_dir=logo_dir)

    # Executive summary
    summary_ax = fig1.add_axes([0.05, 0.83, 0.9, 0.06])
    summary_ax.axis('off')
    summary_text = (
        f"This report summarizes outcomes for {clinic_name} "
        f"in the PATH Lab Psilocybin Therapy Study. Data reflects assessments through the "
        f"{TIMEPOINT_LABELS.get(primary_timepoint, primary_timepoint)} follow-up timepoint."
    )
    summary_ax.text(0, 0.7, summary_text, fontsize=10, color=COLORS['dark'],
                    wrap=True, va='top', ha='left')

    # Section: Key Performance Indicators
    kpi_title = fig1.add_axes([0.05, 0.76, 0.9, 0.04])
    kpi_title.axis('off')
    kpi_title.text(0, 0.5, 'Key Metrics', fontsize=14, fontweight='bold',
                   color=COLORS['dark'], va='center')

    # KPI Cards - 4 cards now including total participants
    ax_kpi0 = fig1.add_axes([0.05, 0.62, 0.21, 0.13])
    create_kpi_card(ax_kpi0, clinic_metrics.get('n_total'),
                    'Total Participants', '',
                    color=COLORS['dark'], is_percent=False)

    ax_kpi1 = fig1.add_axes([0.28, 0.62, 0.21, 0.13])
    create_kpi_card(ax_kpi1, clinic_metrics.get('phq9_response_rate'),
                    'PHQ-9 Response', f'n={clinic_metrics.get("phq9_response_n", 0)}',
                    color=COLORS['primary'])

    ax_kpi2 = fig1.add_axes([0.51, 0.62, 0.21, 0.13])
    create_kpi_card(ax_kpi2, clinic_metrics.get('gad7_response_rate'),
                    'GAD-7 Response', f'n={clinic_metrics.get("gad7_response_n", 0)}',
                    color=COLORS['primary'])

    ax_kpi3 = fig1.add_axes([0.74, 0.62, 0.21, 0.13])
    create_kpi_card(ax_kpi3, clinic_metrics.get('who5_improved_rate'),
                    'WHO-5 Improved', f'n={clinic_metrics.get("who5_response_n", 0)}',
                    color=COLORS['primary'])

    # Section: Comparison to Study
    comp_title = fig1.add_axes([0.05, 0.54, 0.9, 0.04])
    comp_title.axis('off')
    comp_title.text(0, 0.5, 'Comparison to Study Average', fontsize=14, fontweight='bold',
                    color=COLORS['dark'], va='center')

    # Response rate comparisons
    ax_comp1 = fig1.add_axes([0.05, 0.44, 0.42, 0.10])
    create_bar_comparison(ax_comp1, clinic_metrics.get('phq9_response_rate'),
                         study_metrics.get('phq9_response_rate'),
                         'Depression Response Rate', higher_is_better=True)

    ax_comp2 = fig1.add_axes([0.52, 0.44, 0.42, 0.10])
    create_bar_comparison(ax_comp2, clinic_metrics.get('gad7_response_rate'),
                         study_metrics.get('gad7_response_rate'),
                         'Anxiety Response Rate', higher_is_better=True)

    ax_comp3 = fig1.add_axes([0.05, 0.32, 0.42, 0.10])
    create_bar_comparison(ax_comp3, clinic_metrics.get('phq9_remission_rate'),
                         study_metrics.get('phq9_remission_rate'),
                         'Depression Remission Rate', higher_is_better=True)

    ax_comp4 = fig1.add_axes([0.52, 0.32, 0.42, 0.10])
    create_bar_comparison(ax_comp4, clinic_metrics.get('meq_complete_rate'),
                         study_metrics.get('meq_complete_rate'),
                         'Complete Mystical Experience', higher_is_better=True)

    # Section: Score Change Summary
    change_title = fig1.add_axes([0.05, 0.24, 0.9, 0.04])
    change_title.axis('off')
    change_title.text(0, 0.5, 'Average Score Changes (Baseline to ' +
                      TIMEPOINT_LABELS.get(primary_timepoint, primary_timepoint) + ')',
                      fontsize=14, fontweight='bold', color=COLORS['dark'], va='center')

    # Score change summary table
    table_ax = fig1.add_axes([0.05, 0.10, 0.9, 0.13])
    table_ax.axis('off')

    # Create simple table
    measures = ['PHQ-9 (Depression)', 'GAD-7 (Anxiety)', 'WHO-5 (Wellbeing)']
    bl_values = [clinic_metrics.get('phq9_mean_bl', np.nan),
                 clinic_metrics.get('gad7_mean_bl', np.nan),
                 clinic_metrics.get('who5_mean_bl', np.nan)]
    tp_values = [clinic_metrics.get('phq9_mean_tp', np.nan),
                 clinic_metrics.get('gad7_mean_tp', np.nan),
                 clinic_metrics.get('who5_mean_tp', np.nan)]
    changes = [clinic_metrics.get('phq9_mean_change', np.nan),
               clinic_metrics.get('gad7_mean_change', np.nan),
               clinic_metrics.get('who5_mean_change', np.nan)]

    # Table header
    headers = ['Measure', 'Baseline', primary_timepoint.upper(), 'Change']
    for i, h in enumerate(headers):
        table_ax.text(0.05 + i * 0.25, 0.85, h, fontsize=10, fontweight='bold',
                     color=COLORS['dark'], va='center')

    # Table rows
    for row_idx, (measure, bl, tp, change) in enumerate(zip(measures, bl_values, tp_values, changes)):
        y = 0.55 - row_idx * 0.25
        table_ax.text(0.05, y, measure, fontsize=9, color=COLORS['dark'], va='center')
        table_ax.text(0.30, y, f'{bl:.1f}' if not pd.isna(bl) else 'N/A',
                     fontsize=9, color=COLORS['dark'], va='center')
        table_ax.text(0.55, y, f'{tp:.1f}' if not pd.isna(tp) else 'N/A',
                     fontsize=9, color=COLORS['dark'], va='center')

        if not pd.isna(change):
            # Color based on improvement
            if 'WHO' in measure:
                color = COLORS['success'] if change > 0 else COLORS['danger']
                sign = '+' if change > 0 else ''
            else:
                color = COLORS['success'] if change < 0 else COLORS['danger']
                sign = '' if change < 0 else '+'
            table_ax.text(0.80, y, f'{sign}{change:.1f}', fontsize=9,
                         color=color, va='center', fontweight='bold')
        else:
            table_ax.text(0.80, y, 'N/A', fontsize=9, color=COLORS['sage'], va='center')

    create_footer(fig1, logo_dir)

    # === PAGE 2: Trajectories & Distributions ===
    fig2 = plt.figure(figsize=(8.5, 11))
    create_header(fig2, clinic_name, report_title, report_date, page_num=2, total_pages=2, logo_dir=logo_dir)

    # Section title
    traj_title = fig2.add_axes([0.05, 0.84, 0.9, 0.04])
    traj_title.axis('off')
    traj_title.text(0, 0.5, 'Score Trajectories Over Time', fontsize=14, fontweight='bold',
                    color=COLORS['dark'], va='center')

    # Trajectory charts
    ax_traj1 = fig2.add_axes([0.08, 0.62, 0.38, 0.20])
    create_score_trajectory(ax_traj1, df, 'phq9', timepoints,
                           'PHQ-9 (Depression)', (0, 27))

    ax_traj2 = fig2.add_axes([0.55, 0.62, 0.38, 0.20])
    create_score_trajectory(ax_traj2, df, 'gad7', timepoints,
                           'GAD-7 (Anxiety)', (0, 21))

    ax_traj3 = fig2.add_axes([0.08, 0.37, 0.38, 0.20])
    create_score_trajectory(ax_traj3, df, 'who5', timepoints,
                           'WHO-5 (Wellbeing)', (0, 100))

    # Mystical experience distribution
    ax_meq = fig2.add_axes([0.55, 0.37, 0.38, 0.20])
    if 'meq4_total_3d' in df.columns:
        meq_scores = df['meq4_total_3d'].dropna()
        if len(meq_scores) > 0:
            ax_meq.hist(meq_scores, bins=10, color=COLORS['primary'], alpha=0.7,
                       edgecolor=COLORS['dark'])
            ax_meq.axvline(x=3.0, color=COLORS['success'], linestyle='--', linewidth=2,
                          label='Complete mystical (3.0)')
            ax_meq.set_xlabel('MEQ-4 Score', fontsize=9)
            ax_meq.set_ylabel('Count', fontsize=9)
            ax_meq.legend(fontsize=8, loc='upper left')
        else:
            ax_meq.text(0.5, 0.5, 'No data', ha='center', va='center',
                       fontsize=11, color=COLORS['sage'], transform=ax_meq.transAxes)
    ax_meq.set_title('Mystical Experience (MEQ-4)', fontweight='bold', color=COLORS['dark'])

    # Distribution section title
    dist_title = fig2.add_axes([0.05, 0.30, 0.9, 0.04])
    dist_title.axis('off')
    dist_title.text(0, 0.5, 'Score Distributions by Timepoint', fontsize=14, fontweight='bold',
                    color=COLORS['dark'], va='center')

    # Box plots
    ax_box1 = fig2.add_axes([0.08, 0.10, 0.4, 0.18])
    create_distribution_chart(ax_box1, df, 'phq9', timepoints, 'PHQ-9')

    ax_box2 = fig2.add_axes([0.55, 0.10, 0.4, 0.18])
    create_distribution_chart(ax_box2, df, 'gad7', timepoints, 'GAD-7')

    create_footer(fig2, logo_dir)

    # Save both pages to PDF
    with PdfPages(output_path) as pdf:
        pdf.savefig(fig1, bbox_inches='tight', dpi=150,
                    facecolor=COLORS['white'], edgecolor='none')
        pdf.savefig(fig2, bbox_inches='tight', dpi=150,
                    facecolor=COLORS['white'], edgecolor='none')

    plt.close('all')
    print(f"Generated report: {output_path}")
    return output_path


def main():
    """Generate example clinic reports with positive outcomes."""
    # Load data
    data_path = Path(__file__).parent.parent / 'data' / 'insights.csv'
    df = pd.read_csv(data_path)

    output_dir = Path(__file__).parent.parent / 'reports'
    output_dir.mkdir(exist_ok=True)

    # Use subset of participants with positive outcomes across all measures
    # For Q2 (3mo): IDs with positive change at 3mo
    positive_3mo_ids = [2, 9, 14, 25, 26, 30, 31, 46, 48, 72, 73, 75, 76, 84, 85, 107, 112]
    # For Q4 (6mo): IDs with positive change at 6mo
    positive_6mo_ids = [19, 30, 31, 52, 75, 87, 90, 94]

    clinic_df_q2 = df[df['record_id'].isin(positive_3mo_ids)]
    clinic_df_q4 = df[df['record_id'].isin(positive_6mo_ids)]

    # Generate Q2 report (mid-year, showing through 3mo)
    generate_clinic_report(
        clinic_df_q2,
        clinic_name='Example Clinic',
        report_type='Q2',
        output_path=output_dir / 'clinic_report_Q2_example.pdf',
        study_df=df
    )

    # Generate Q4 report (annual, showing through 6mo/12mo)
    generate_clinic_report(
        clinic_df_q4,
        clinic_name='Example Clinic',
        report_type='Q4',
        output_path=output_dir / 'clinic_report_Q4_example.pdf',
        study_df=df
    )

    print(f"\nReports saved to: {output_dir}")


if __name__ == '__main__':
    main()
